[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
addopts = "-v --tb=short"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.0.0"
pytest-check = "^2.1.4"
pytest-cov = "^4.1.0" 